AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/google-oauth-cli.rb'
    - 'spec/google-oauth-cli_spec.rb'

Metrics/BlockLength:
  Max: 28

Metrics/MethodLength:
  Max: 15
